language: ruby

rvm: 
  - 2.5.3

# before_script:
#   - chmod +x ./script/cibuild

script:
  # - ./script/cibuild
  - bundle exec jekyll build --destination _site

branches:
  only:
    - /Patch-*.*_I*

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler