language: ruby

rvm: 
  - 2.5.0

before_script:
 - chmod +x ./script/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

cache: bundler