# List of Interject formula doc pages to parse for metadata

from enum import Enum

class InterjectFormulas(Enum):
    REPORT_RANGE = "ReportRange.md"
    REPORT_FIXED = "ReportFixed.md"
    REPORT_VARIABLE = "ReportVariable.md"
    REPORT_LOOKUP = "ReportLookup.md"
    REPORT_SAVE = "ReportSave.md"
    REPORT_DRILL = "ReportDrill.md"
    REPORT_MACRO = "ReportMacro.md"
    REPORT_RUN = "ReportRun.md"
    REPORT_CALC = "ReportCalc.md"
    REPORT_DEFAULTS = "ReportDefaults.md"
    REPORT_GROUPING = "ReportGrouping.md"
    REPORT_HIDE_ROW_OR_COLUMN = "ReportHideRowOrColumn.md"
    JDROPDOWN = "jDropdown.md"
    JFOCUS = "jFocus.md"
    JFREEZE_PANES = "jFreezePanes.md"
    JCOMBINE = "jCombine.md"
    JCOMBINE_IF = "jCombineIf.md"
    JCOMBINE_SMART = "jCombineSmart.md"
    JCOLUMN_DEF = "jColumnDef.md"
    JRANGE_TAG = "jRangeTag.md"
    JWORKBOOK_PROPERTY = "jWorkbookProperty.md"
    JSETTING = "jSetting.md"
    PAIR = "Pair.md"
    PAIR_GROUP = "PairGroup.md"
    PARAM = "Param.md"
    JACCT = "jAcct.md"
    JCELL = "jCell.md"
    JCELLN = "jCell.md"
    JDESC = "jDesc.md"
